BEGIN;

CREATE TABLE clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL CHECK (btrim(name) <> ''),
    email VARCHAR(64) NOT NULL UNIQUE CHECK (email <> '' AND email = lower(btrim(email))),
    phone VARCHAR(30)
);

CREATE TABLE translation_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE RESTRICT,
    title VARCHAR(200) NOT NULL CHECK (btrim(title) <> ''),
    description TEXT,
    source_language VARCHAR(50) NOT NULL CHECK (btrim(source_language) <> ''),
    target_language VARCHAR(50) NOT NULL CHECK (btrim(target_language) <> ''),
    word_count INTEGER NOT NULL CHECK (word_count > 0),
    price NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'NEW'
        CHECK (status IN ('NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deadline DATE NOT NULL,
    CHECK (lower(btrim(source_language)) <> lower(btrim(target_language))),
    CHECK (deadline >= created_at::date)
);

CREATE INDEX idx_translation_orders_client_id ON translation_orders(client_id);

COMMIT;
